# K8s resources to watch
[resources]
    [resources.deployment]
        policies = [
            "cleanReplicasIfPodAutoscaling"
        ]

# Handlers will be trigger in this specific order
# Diff handler should typically be the first handler to trigger
[[handlers]]
name       = "diff"

[[handlers]]
name        = "slack"
clusterName = "myClusterName"
webhookURL  = "https://xxx.slack.com"
