## List of resources to watch
[[resource]]
kind = "deployment"

[[resource]]
kind = "service"

[[resource]]
kind = "statefulset"

[[resource]]
kind = "daemonset"

[[resource]]
kind = "ingress"

## Handlers to run, executed in its configured order
[[handler]]
name = "diff"

[[handler]]
name = "log"

#[[handler]]
#name = "ignoreEvents"
#events = ["Add", "Update", "Delete"]

#[[handler]]
#name        = "slack"
#clusterName = "myClusterName"
#webhookURL  = "https://slack-webhook-url"
